language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - pip install coveralls
  - pip wheel --wheel-dir=/tmp/wheelhouse codeink
  - pip install --no-index --find-links=/tmp/wheelhouse codeink
#  - python setup.py sdist bdist_wheel
#  - pip install --use-wheel --no-index --find-links=./dist
#  - pip install .

script:
  # artist.py doesnt contain any logic by itself but rather high level abstractions
  - coverage run --source=codeink --omit=*artist.py -m py.test -vv

after_success:
  - coveralls
