language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - pip install coveralls
  - pip install .

script:
  - coverage run --source=codeink -m py.test -vv
  # artist.py doesnt contain any logic by itself but rather high level abstractions
  - coverage report --omit=./codeink/artist.py

after_success:
  - coveralls
